services:
  redis:
    image: redis:7.2.3-alpine
    command: >
      --notify-keyspace-events KEA
    networks:
      - brainbot
  
  server:
    image: brainbot/server:0.0.1
    depends_on:
      - redis
    env_file:
      - ./.env.prod
    networks:
      - brainbot
    ports:
      - 4095:4095

  brainbot:
    image: brainbot:0.0.3
    depends_on:
      - redis
      - server
    networks:
      - brainbot
    volumes:
      - type: bind
        source: ./chat/lnks/list.txt
        target: /home/runner/bot/chat/list.txt
      - type: bind
        source: ./.env.dev
        target: /home/runner/bot/.env

networks:
  brainbot: