services:
  redis:
    image: redis:7.2.3-alpine
    command: >
      --notify-keyspace-events KEA
    networks:
      - brainbot_dev
    ports:
      - 6379:6379
  
  server:
    entrypoint: sh -c "npm install --include=dev && npm run dev"
    depends_on:
      - redis
    env_file: 
      - ./.env.dev
    image: node:20.11-alpine
    networks:
      - brainbot_dev
    ports:
      - 4095:4095
    volumes:
      - type: bind
        source: ./server/
        target: /app/server/
    working_dir: /app/server

  chat:
    entrypoint: sh -c "pip install redis requests && python3 -u ./main.py"
    depends_on:
      - redis
    env_file:
      - ./.env.dev
    image: python:alpine
    networks:
      - brainbot_dev
    volumes:
      - type: bind
        source: ./chat/
        target: /chat/
    working_dir: /chat

  bot:
    entrypoint: sh -c "\
         cmake -B ./build \
      && cmake --build ./build \
      && ./build/brainbot"
    image: brainbot/env:latest
    networks:
      - brainbot_dev
    tty: true
    volumes:
      - type: bind
        source: ./bot/
        target: /home/runner/bot
      - type: bind
        source: ./.env.dev
        target: /home/runner/bot/.env
    working_dir: /home/runner/bot

networks:
  brainbot_dev: