name: Bot environment CI

on:
    workflow_dispatch:
    push:
        paths:
            - 'bot/libs/**'

jobs:
    build-image:
        name: Build Image
        runs-on: ubuntu-latest
        environment: LIBRARY
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Load signing key
              shell: bash
              run: |
                echo "$SIGN_PRIV_KEY" > ./bot/.abuild/key.rsa
                echo "$SIGN_PUB_KEY" > ./bot/.abuild/key.rsa.pub
              env: 
                SIGN_PRIV_KEY: ${{secrets.SIGN_PRIV_KEY}}
                SIGN_PUB_KEY: ${{secrets.SIGN_PUB_KEY}}

            - name: Build packager image
              run: docker build bot -f bot/Dockerfile.lib -t brainbot/lib:latest

            - name: Build bot's library
              run: |
                sudo mkdir -p bot/.abuild/packages
                sudo docker compose -f docker-compose.lib.yaml up

            - name: Build base runner image
              run: docker build bot -f bot/Dockerfile.env -t brainbot/env:latest

            - name: Save the base runner image
              run: docker image save -o brainbot-env.tar.gz brainbot-env:latest

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: brainbot-env
                path: brainbot-env.tar.gz
