name: Bot library CI

on:
    workflow_dispatch:
    push:
        paths:
            - 'bot/libs/**'

jobs:
    build-library:
        name: Build library
        runs-on: ubuntu-latest
        environment: LIBRARY
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Load signing key
              shell: bash
              run: |
                echo "$SIGN_PRIV_KEY" > ./bot/.abuild/mschodeihsan@gmail.com-6625473b.rsa
                echo "$SIGN_PUB_KEY" > ./bot/.abuild/mschodeihsan@gmail.com-6625473b.rsa.pub
              env: 
                SIGN_PRIV_KEY: ${{secrets.SIGN_PRIV_KEY}}
                SIGN_PUB_KEY: ${{secrets.SIGN_PUB_KEY}}

            - name: Build packager image
              run: docker build bot -f bot/Dockerfile.lib -t brainbot/lib:latest

            - name: Build bot's library
              run: |
                mkdir -p ./bot/.abuild/packages
                chmod 777 ./bot/.abuild/packages
                ls -la ./bot/.abuild/
                cat ./bot/.abuild/key.rsa.pub
                docker compose -f docker-compose.lib.yaml up

            - name: Upload library artifact
              uses: actions/upload-artifact@v4
              with:
                name: packages
                path: bot/.abuild/packages
